spring:

    datasource:
        url: jdbc:mysql://localhost/appelenenperen
        username: appelen
        password: appelen

    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
          current_session_context_class: org.springframework.orm.hibernate4.SpringSessionContext

logging:
  file: logfile.txt
  level:
    root:  info
    
server:
  port: 8080
            